In [1]:
my_list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
my_list2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [5]:
np.array(my_list2)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.arange(2,10,3)

array([2, 5, 8])

In [10]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
#eye lineer cebir için

In [16]:
np.random.rand(5)

array([0.96081859, 0.09092273, 0.23837153, 0.45962468, 0.82216684])

In [19]:
np.random.randn(5,5)

array([[ 1.57864325, -0.1266322 ,  0.02438299, -0.6736972 ,  1.38070742],
       [-0.45141854,  1.54170517,  0.64751333,  1.01985016, -0.16819981],
       [ 1.55476344,  0.11751465, -1.60176334, -0.42161601, -0.3664342 ],
       [ 0.24580447, -0.49971531,  0.24917463, -1.2218108 , -0.2430718 ],
       [ 0.00234897,  0.24489873, -0.93825913, -0.96038041,  1.27944384]])

In [20]:
np.random.randint(1,100,5)

array([95, 25, 54, 87, 52])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,100,10)

In [38]:
ranarr

array([45, 22, 58, 61, 55, 99, 40, 91, 60, 15])

In [39]:
ranarr.max()

99

In [41]:
ranarr.argmin()

9

In [42]:
ranarr.argmax()

5

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(25,)

In [44]:
arr2 = arr.reshape(5,5)

In [45]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr2.shape

(5, 5)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr2.dtype

dtype('int32')

In [48]:
from numpy.random import randint

In [79]:
randint(2,10)

5

In [ ]:
#İndexing

In [50]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [51]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr_2d[1,1]

5

In [54]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [55]:
arr = np.arange(0,10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [58]:
boolen_arr = arr > 4

In [59]:
boolen_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
arr[boolen_arr]

array([5, 6, 7, 8, 9])

In [62]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [63]:
arr3 = np.arange(50).reshape(5,10)

In [64]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
arr3[3:,6:8]

array([[36, 37],
       [46, 47]])

In [ ]:
#Arithmetic Operations

In [67]:
arr = np.arange(1,11)

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [74]:
arr.max()

10

In [75]:
np.max(arr)

10

In [76]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [77]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [80]:
import numpy as np

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
arr = np.arange(10)
arr[:] = 5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [86]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [87]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [89]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.random.rand(1)

array([0.15052216])

In [98]:
np.random.randn(25).reshape(5,5)

array([[-0.34650114, -0.35966847, -0.929799  , -1.44431786,  1.28947237],
       [ 0.69869763,  0.34938843,  0.79053686,  1.10352735, -0.42899021],
       [-0.02805492, -1.43655103, -0.20797909, -0.19773458, -0.97417066],
       [ 0.37560866, -1.89310776,  0.91457433, -0.36058112,  1.93761021],
       [-1.03534153, -0.50982394,  0.03647562,  2.06934956, -0.16339269]])

In [102]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])