In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:6]

In [10]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:] = 99

In [12]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Yukarıda arr[0:6] yı slice_of_arr'a assign ettim ama bu referans gibi çalıştı. Bunun yerine copy methodunu kullanmalıyız.

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 20

In [17]:
arr_copy

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

yukarda görüldüğü gibi COPY methodu sayesinde arr içinde bir değişiklik olmuyor

--------------------------MATRIX-----------------------

In [19]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr2d[1][1]

5

In [21]:
arr2d[1,1]

5

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2d.dtype

dtype('int32')

In [24]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

-----------Conditional Situations----------------

In [33]:
arr2 = np.arange(0,11)

In [34]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr2 > 5

In [39]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [40]:
arr2[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr2[arr2>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr2[arr2<3]

array([0, 1, 2])

In [43]:
arr_2d = np.arange(50).reshape(5,10)

In [44]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2d[1,3:6]

array([13, 14, 15])