In [1]:
lst = [1,2,3,4,5]

In [2]:
lst

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
twoDim = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
twoDim

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
twoDimArr = np.array(twoDim)

In [9]:
twoDimArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.linspace(0,7,8)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [21]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Standart Matrix Oluşturma


In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(4)

array([0.48121546, 0.19988907, 0.92954161, 0.77648476])

In [23]:
np.random.rand(3,3)

array([[0.31730991, 0.0994273 , 0.56766673],
       [0.76752392, 0.53255245, 0.46157108],
       [0.58004533, 0.43820532, 0.91470779]])

In [24]:
np.random.randn(4)

array([-0.91406709,  0.1226755 , -1.64169627,  0.05271528])

In [25]:
np.random.randn(3,4)

array([[ 2.1414914 , -1.69395548, -0.85048169, -0.88183525],
       [-0.21872886, -0.33299691,  0.00434193,  0.64682143],
       [-1.1089664 ,  1.015452  , -1.09274379,  1.57307204]])

2 Sayı Arasında random integer oluşturma

In [26]:
np.random.randint(0,12)

2

In [27]:
np.random.randint(0,20,5)

array([10,  4,  0,  3, 19])

np.arange Ardışık Aayı Atarken np.random.randint Random Sayı Atar.

In [28]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
np.random.randint(0,50,25)

array([19,  7, 23, 44, 32, 13, 15, 45, 19, 48, 47, 25, 20, 32, 46, 33, 19,
       24, 38, 34, 19,  7, 26, 14, 40])

-
np.reshape Halihazırda Varolan array'i Two Dimension Hale Getirir
-

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
randArr = np.random.randint(0,50,25)

In [33]:
randArr

array([30,  3, 40, 13, 25, 26, 16, 45,  5, 46, 41, 44,  5, 19,  4,  5,  0,
       33, 33, 49,  2,  0, 41, 16, 34])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
randArr.reshape(5,5)

array([[30,  3, 40, 13, 25],
       [26, 16, 45,  5, 46],
       [41, 44,  5, 19,  4],
       [ 5,  0, 33, 33, 49],
       [ 2,  0, 41, 16, 34]])

In [37]:
randArr.min()

0

In [41]:
randArr.max()

49

argmin En Küçük Sayının Indexini -- argmax ise En Büyük Sayının Indexini Bulur

In [39]:
randArr.argmin()

16

In [40]:
randArr.argmax()

19

In [43]:
arr.shape

(25,)

In [44]:
randArr.shape

(25,)

In [45]:
arr2 = arr.reshape(5,5)

In [46]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr2.shape

(5, 5)

In [49]:
from numpy.random import randint

In [50]:
randint(0,5)

3

In [67]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [62]:
np.linspace(0,1,20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])